<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Item;

class ItemSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $items = [
            [
                'item_category_id' => 18,
                'unit_of_measure_id' => 19,
                'item_code' => "78111501-GFA-001",
                'item_name' => '* Airline Ticket',
            ],
            [
                'item_category_id' => 7,
                'unit_of_measure_id' => 17,
                'item_code' => "13111203-AC-F01",
                'item_name' => 'ACETATE, thickness: 0.075mm min (gauge #3)',
            ],
            [
                'item_category_id' => 4,
                'unit_of_measure_id' => 1,
                'item_code' => "47131812-AF-A01",
                'item_name' => 'AIR FRESHENER, aerosol, 280ml/150g min',
            ],
            [
                'item_category_id' => 25,
                'unit_of_measure_id' => 8,
                'item_code' => "12191601-AL-E02",
                'item_name' => 'ALCOHOL, ethyl, 68%-72%, scented, 3.785 liters',
            ],
            [
                'item_category_id' => 25,
                'unit_of_measure_id' => 4,
                'item_code' => "12191601-AL-E01",
                'item_name' => 'ALCOHOL, ethyl, 68%-72%, scented, 500ml (-5ml)',
            ],
            [
                'item_category_id' => 25,
                'unit_of_measure_id' => 4,
                'item_code' => "51471901-AL-I01",
                'item_name' => 'ALCOHOL, isopropyl, 68%- 72%, 500ml (-5ml)',
            ],
            [
                'item_category_id' => 25,
                'unit_of_measure_id' => 8,
                'item_code' => "51471901-AL-I02",
                'item_name' => 'ALCOHOL, isopropyl, 68%-72%, scented, 3.785 liters',
            ],
            [
                'item_category_id' => 3,
                'unit_of_measure_id' => 12,
                'item_code' => "26111702-BT-A01",
                'item_name' => 'BATTERY, dry cell, AA, 2 pieces per blister pack',
            ],
            [
                'item_category_id' => 3,
                'unit_of_measure_id' => 12,
                'item_code' => "26111702-BT-A02",
                'item_name' => 'BATTERY, dry cell, AAA, 2 pieces per blister pack',
            ],
            [
                'item_category_id' => 3,
                'unit_of_measure_id' => 12,
                'item_code' => "26111702-BT-A03",
                'item_name' => 'BATTERY, dry cell, D, 1.5 volts, alkaline',
            ],
            [
                'item_category_id' => 16,
                'unit_of_measure_id' => 20,
                'item_code' => "44101602-PB-M01",
                'item_name' => 'BINDING AND PUNCHING MACHINE, binding cap: 50mm',
            ],
            [
                'item_category_id' => 4,
                'unit_of_measure_id' => 15,
                'item_code' => "47131604-BR-S01",
                'item_name' => 'BROOM, soft (tambo)',
            ],
            [
                'item_category_id' => 4,
                'unit_of_measure_id' => 15,
                'item_code' => "47131604-BR-T01",
                'item_name' => 'BROOM, STICK (TING-TING), usable length: 760mm min',
            ],
            [
                'item_category_id' => 24,
                'unit_of_measure_id' => 10,
                'item_code' => "43230000-SFT-001",
                'item_name' => 'Business function specific software',
            ],
            [
                'item_category_id' => 16,
                'unit_of_measure_id' => 20,
                'item_code' => "44101807-CA-C01",
                'item_name' => 'CALCULATOR, compact, 12 digits',
            ],
            [
                'item_category_id' => 7,
                'unit_of_measure_id' => 5,
                'item_code' => "13111201-CF-P02",
                'item_name' => 'CARBON FILM, PE, black, size 210mm x 297mm',
            ],
            [
                'item_category_id' => 7,
                'unit_of_measure_id' => 5,
                'item_code' => "13111201-CF-P02",
                'item_name' => 'CARBON FILM, PE, black, size 216mm x 330mm',
            ],
            [
                'item_category_id' => 19,
                'unit_of_measure_id' => 12,
                'item_code' => "14111525-CA-A01",
                'item_name' => 'CARTOLINA, assorted colors',
            ],
            [
                'item_category_id' => 10,
                'unit_of_measure_id' => 15,
                'item_code' => "56101504-CM-B01",
                'item_name' => 'CHAIR, monobloc, beige, with backrest, w/o armrest',
            ],
            [
                'item_category_id' => 10,
                'unit_of_measure_id' => 15,
                'item_code' => "56101504-CM-W01",
                'item_name' => 'CHAIR,monobloc, white, with backrest, w/o armrest',
            ],
            [
                'item_category_id' => 16,
                'unit_of_measure_id' => 5,
                'item_code' => "44121710-CH-W01",
                'item_name' => 'CHALK, molded, white, dustless, length: 78mm min',
            ],
            [
                'item_category_id' => 4,
                'unit_of_measure_id' => 4,
                'item_code' => "47131829-TB-C01",
                'item_name' => 'CLEANER,TOILET BOWL AND URINAL, 900ml-1000ml cap',
            ],
            [
                'item_category_id' => 4,
                'unit_of_measure_id' => 1,
                'item_code' => "47131805-CL-P01",
                'item_name' => 'CLEANSER, SCOURING POWDER, 350g min./can',
            ],
            [
                'item_category_id' => 1,
                'unit_of_measure_id' => 15,
                'item_code' => "60121413-CB-P01",
                'item_name' => 'CLEARBOOK, 20 transparent pockets, for A4 size',
            ],
            [
                'item_category_id' => 1,
                'unit_of_measure_id' => 15,
                'item_code' => "60121413-CB-P02",
                'item_name' => 'CLEARBOOK, 20 transparent pockets, for LEGAL size',
            ],
            [
                'item_category_id' => 16,
                'unit_of_measure_id' => 5,
                'item_code' => "44122105-BF-C01",
                'item_name' => 'CLIP, BACKFOLD, all metal, clamping: 19mm (-1mm)',
            ],
            [
                'item_category_id' => 16,
                'unit_of_measure_id' => 5,
                'item_code' => "44122105-BF-C02",
                'item_name' => 'CLIP, BACKFOLD, all metal, clamping: 25mm (-1mm)',
            ],
            [
                'item_category_id' => 16,
                'unit_of_measure_id' => 5,
                'item_code' => "44122105-BF-C03",
                'item_name' => 'CLIP, BACKFOLD, all metal, clamping: 32mm (-1mm)',
            ],
            [
                'item_category_id' => 16,
                'unit_of_measure_id' => 5,
                'item_code' => "44122105-BF-C04",
                'item_name' => 'CLIP, BACKFOLD, all metal, clamping: 50mm (-1mm)',
            ],
            [
                'item_category_id' => 24,
                'unit_of_measure_id' => 10,
                'item_code' => "43230000-SFT-003",
                'item_name' => 'Computer game or entertainment software',
            ],
            [
                'item_category_id' => 24,
                'unit_of_measure_id' => 10,
                'item_code' => "43230000-SFT-004",
                'item_name' => 'Content authoring and editing software',
            ],
            [
                'item_category_id' => 24,
                'unit_of_measure_id' => 10,
                'item_code' => "43230000-SFT-005",
                'item_name' => 'Content management software',
            ],
            [
                'item_category_id' => 19,
                'unit_of_measure_id' => 5,
                'item_code' => "14111506-CF-L11",
                'item_name' => 'CONTINUOUS FORM, 1 PLY, 280 x 241mm',
            ],
            [
                'item_category_id' => 19,
                'unit_of_measure_id' => 5,
                'item_code' => "14111506-CF-L12",
                'item_name' => 'CONTINUOUS FORM, 1 PLY, 280 x 378mm',
            ],
            [
                'item_category_id' => 19,
                'unit_of_measure_id' => 5,
                'item_code' => "14111506-CF-L22",
                'item_name' => 'CONTINUOUS FORM, 2 ply, 280 x 378mm, carbonless',
            ],
            [
                'item_category_id' => 19,
                'unit_of_measure_id' => 5,
                'item_code' => "14111506-CF-L21",
                'item_name' => 'CONTINUOUS FORM, 2 ply, 280mm x 241mm, carbonless',
            ],
            [
                'item_category_id' => 19,
                'unit_of_measure_id' => 5,
                'item_code' => "14111506-CF-L31",
                'item_name' => 'CONTINUOUS FORM, 3 PLY, 280 x 241mm, carbonless',
            ],
            [
                'item_category_id' => 19,
                'unit_of_measure_id' => 5,
                'item_code' => "14111506-CF-L32",
                'item_name' => 'CONTINUOUS FORM, 3 PLY, 280 x 378mm, carbonless',
            ],
            [
                'item_category_id' => 16,
                'unit_of_measure_id' => 15,
                'item_code' => "44121801-CT-R01",
                'item_name' => 'CORRECTION TAPE, film base type, UL 6m min',
            ],
            [
                'item_category_id' => 16,
                'unit_of_measure_id' => 15,
                'item_code' => "44121612-BL-H01",
                'item_name' => 'CUTTER BLADE, for heavy duty cutter',
            ],
            [
                'item_category_id' => 16,
                'unit_of_measure_id' => 15,
                'item_code' => "44121612-CU-H01",
                'item_name' => 'CUTTER KNIFE, for general purpose',
            ],
            [
                'item_category_id' => 16,
                'unit_of_measure_id' => 15,
                'item_code' => "44111515-DF-B01",
                'item_name' => 'DATA FILE BOX, made of chipboard, with closed ends',
            ],
            [
                'item_category_id' => 16,
                'unit_of_measure_id' => 15,
                'item_code' => "44122011-DF-F01",
                'item_name' => 'DATA FOLDER, made of chipboard, taglia lock',
            ],
            [
                'item_category_id' => 24,
                'unit_of_measure_id' => 10,
                'item_code' => "43230000-SFT-006",
                'item_name' => 'Data management and query software',
            ],
            [
                'item_category_id' => 16,
                'unit_of_measure_id' => 15,
                'item_code' => "44103202-DS-M01",
                'item_name' => 'DATING AND STAMPING MACHINE, heavy duty',
            ],
            [
                'item_category_id' => 12,
                'unit_of_measure_id' => 20,
                'item_code' => "43211507-DCT-03",
                'item_name' => 'Desktop Computer, branded',
            ],
            [
                'item_category_id' => 4,
                'unit_of_measure_id' => 2,
                'item_code' => "47131811-DE-B02",
                'item_name' => 'DETERGENT BAR, 140 grams as packed',
            ],
            [
                'item_category_id' => 4,
                'unit_of_measure_id' => 12,
                'item_code' => "47131811-DE-P02",
                'item_name' => 'DETERGENT POWDER, all purpose, 1kg',
            ],
            [
                'item_category_id' => 24,
                'unit_of_measure_id' => 10,
                'item_code' => "43230000-SFT-007",
                'item_name' => 'Development software',
            ],
            [
                'item_category_id' => 6,
                'unit_of_measure_id' => 20,
                'item_code' => "52161535-DV-R01",
                'item_name' => 'DIGITAL VOICE RECORDER, memory: 4GB (expandable)',
            ],
            [
                'item_category_id' => 4,
                'unit_of_measure_id' => 1,
                'item_code' => "47131803-DS-A01",
                'item_name' => 'DISINFECTANT SPRAY, aerosol type, 400-550 grams',
            ],
            [
                'item_category_id' => 2,
                'unit_of_measure_id' => 20,
                'item_code' => "45121517-DO-C01",
                'item_name' => 'DOCUMENT CAMERA, 3.2M pixels',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103109-BR-D05",
                'item_name' => 'DRUM CART, BROTHER DR-3455',
            ],
            [
                'item_category_id' => 4,
                'unit_of_measure_id' => 15,
                'item_code' => "47131601-DU-P01",
                'item_name' => 'DUST PAN, non-rigid plastic, w/ detachable handle',
            ],
            [
                'item_category_id' => 12,
                'unit_of_measure_id' => 15,
                'item_code' => "43202003-DV-W01",
                'item_name' => 'DVD REWRITABLE, speed: 4x min, 4.7GB capacity min',
            ],
            [
                'item_category_id' => 24,
                'unit_of_measure_id' => 10,
                'item_code' => "43230000-SFT-008",
                'item_name' => 'Educational or reference software',
            ],
            [
                'item_category_id' => 11,
                'unit_of_measure_id' => 20,
                'item_code' => "40101604-EF-G01",
                'item_name' => 'ELECTRIC FAN, INDUSTRIAL, ground type, metal blade',
            ],
            [
                'item_category_id' => 11,
                'unit_of_measure_id' => 20,
                'item_code' => "40101604-EF-C01",
                'item_name' => 'ELECTRIC FAN, ORBIT type, ceiling, metal blade',
            ],
            [
                'item_category_id' => 11,
                'unit_of_measure_id' => 20,
                'item_code' => "40101604-EF-S01",
                'item_name' => 'ELECTRIC FAN, STAND type, plastic blade',
            ],
            [
                'item_category_id' => 11,
                'unit_of_measure_id' => 20,
                'item_code' => "40101604-EF-W01",
                'item_name' => 'ELECTRIC FAN, WALL type, plastic blade',
            ],
            [
                'item_category_id' => 16,
                'unit_of_measure_id' => 5,
                'item_code' => "44121506-EN-D01",
                'item_name' => 'ENVELOPE, DOCUMENTARY, for A4 size document',
            ],
            [
                'item_category_id' => 16,
                'unit_of_measure_id' => 5,
                'item_code' => "44121506-EN-D02",
                'item_name' => 'ENVELOPE, DOCUMENTARY, for legal size document',
            ],
            [
                'item_category_id' => 16,
                'unit_of_measure_id' => 5,
                'item_code' => "44121506-EN-X01",
                'item_name' => 'ENVELOPE, EXPANDING, KRAFTBOARD,for legal size doc',
            ],
            [
                'item_category_id' => 16,
                'unit_of_measure_id' => 15,
                'item_code' => "44121506-EN-X02",
                'item_name' => 'ENVELOPE, EXPANDING, PLASTIC, 0.50mm thickness min',
            ],
            [
                'item_category_id' => 16,
                'unit_of_measure_id' => 5,
                'item_code' => "44121504-EN-W01",
                'item_name' => 'ENVELOPE, mailing, white, with window',
            ],
            [
                'item_category_id' => 16,
                'unit_of_measure_id' => 5,
                'item_code' => "44121506-EN-M01",
                'item_name' => 'ENVELOPE, MAILING,white, 80gsm (-5%)',
            ],
            [
                'item_category_id' => 16,
                'unit_of_measure_id' => 15,
                'item_code' => "44111912-ER-B01",
                'item_name' => 'ERASER, FELT, for blackboard/whiteboard',
            ],
            [
                'item_category_id' => 1,
                'unit_of_measure_id' => 15,
                'item_code' => "60121534-ER-P01",
                'item_name' => 'ERASER, PLASTIC/RUBBER, for pencil draft/writing',
            ],
            [
                'item_category_id' => 12,
                'unit_of_measure_id' => 15,
                'item_code' => "43201827-HD-X02",
                'item_name' => 'EXTERNAL HARD DRIVE, 1TB, 2.5"HDD, USB 3.0',
            ],
            [
                'item_category_id' => 16,
                'unit_of_measure_id' => 20,
                'item_code' => "44101714-FX-M01",
                'item_name' => 'FACSIMILE MACHINE, uses thermal paper',
            ],
            [
                'item_category_id' => 16,
                'unit_of_measure_id' => 5,
                'item_code' => "44122118-FA-P01",
                'item_name' => 'FASTENER, METAL, 70mm between prongs',
            ],
            [
                'item_category_id' => 16,
                'unit_of_measure_id' => 15,
                'item_code' => "44111515-FO-X01",
                'item_name' => 'FILE ORGANIZER, expanding, plastic, 12 pockets',
            ],
            [
                'item_category_id' => 16,
                'unit_of_measure_id' => 18,
                'item_code' => "44122018-FT-D01",
                'item_name' => 'FILE TAB DIVIDER, bristol board, for A4',
            ],
            [
                'item_category_id' => 16,
                'unit_of_measure_id' => 18,
                'item_code' => "44122018-FT-D02",
                'item_name' => 'FILE TAB DIVIDER, bristol board, for legal',
            ],
            [
                'item_category_id' => 24,
                'unit_of_measure_id' => 10,
                'item_code' => "43230000-SFT-002",
                'item_name' => 'Finance accounting and enterprise resource planning ERP software',
            ],
            [
                'item_category_id' => 8,
                'unit_of_measure_id' => 20,
                'item_code' => "46191601-FE-M01",
                'item_name' => 'FIRE EXTINGUISHER, DRY CHEMICAL, 4.5kgs',
            ],
            [
                'item_category_id' => 8,
                'unit_of_measure_id' => 20,
                'item_code' => "46191601-FE-H01",
                'item_name' => 'FIRE EXTINGUISHER, PURE HCFC 123, 4.5kgs',
            ],
            [
                'item_category_id' => 12,
                'unit_of_measure_id' => 15,
                'item_code' => "43202010-FD-U01",
                'item_name' => 'FLASH DRIVE, 16 GB capacity',
            ],
            [
                'item_category_id' => 4,
                'unit_of_measure_id' => 1,
                'item_code' => "47131802-FW-P02",
                'item_name' => 'FLOOR WAX, PASTE, RED',
            ],
            [
                'item_category_id' => 13,
                'unit_of_measure_id' => 15,
                'item_code' => "39101605-FL-T01",
                'item_name' => 'FLUORESCENT LAMP, 18 WATTS, linear tubular (T8)',
            ],
            [
                'item_category_id' => 16,
                'unit_of_measure_id' => 6,
                'item_code' => "44122011-FO-F01",
                'item_name' => 'FOLDER, FANCY, for A4 size documents',
            ],
            [
                'item_category_id' => 16,
                'unit_of_measure_id' => 6,
                'item_code' => "44122011-FO-F02",
                'item_name' => 'FOLDER, FANCY, for legal size documents',
            ],
            [
                'item_category_id' => 16,
                'unit_of_measure_id' => 12,
                'item_code' => "44122011-FO-L01",
                'item_name' => 'FOLDER, L-TYPE, PLASTIC, for A4 size documents',
            ],
            [
                'item_category_id' => 16,
                'unit_of_measure_id' => 12,
                'item_code' => "44122011-FO-L02",
                'item_name' => 'FOLDER, L-TYPE, PLASTIC, for legal size documents',
            ],
            [
                'item_category_id' => 16,
                'unit_of_measure_id' => 5,
                'item_code' => "44122027-FO-P01",
                'item_name' => 'FOLDER, PRESSBOARD, size: 240mm x 370mm (-5mm)',
            ],
            [
                'item_category_id' => 16,
                'unit_of_measure_id' => 12,
                'item_code' => "44122011-FO-T03",
                'item_name' => 'FOLDER, TAGBOARD, for A4 size documents',
            ],
            [
                'item_category_id' => 16,
                'unit_of_measure_id' => 12,
                'item_code' => "44122011-FO-T04",
                'item_name' => 'FOLDER, TAGBOARD, for legal size documents',
            ],
            [
                'item_category_id' => 4,
                'unit_of_measure_id' => 1,
                'item_code' => "47131830-FC-A01",
                'item_name' => 'FURNITURE CLEANER, aerosol type, 300ml min per can',
            ],
            [
                'item_category_id' => 14,
                'unit_of_measure_id' => 9,
                'item_code' => "31201610-GL-J01",
                'item_name' => 'GLUE, all purpose, gross weight: 200 grams min',
            ],
            [
                'item_category_id' => 23,
                'unit_of_measure_id' => 4,
                'item_code' => "53131626-HS-S01",
                'item_name' => 'HAND SANITIZER, 500 ml',
            ],
            [
                'item_category_id' => 21,
                'unit_of_measure_id' => 3,
                'item_code' => "55101524-RA-H01",
                'item_name' => 'HANDBOOK (RA 9184), 7th Edition',
            ],
            [
                'item_category_id' => 12,
                'unit_of_measure_id' => 20,
                'item_code' => "",
                'item_name' => 'Hub/Switches',
            ],
            [
                'item_category_id' => 16,
                'unit_of_measure_id' => 5,
                'item_code' => "44122008-IT-T01",
                'item_name' => 'INDEX TAB, self-adhesive, transparent',
            ],
            [
                'item_category_id' => 24,
                'unit_of_measure_id' => 10,
                'item_code' => "43230000-SFT-009",
                'item_name' => 'Industry specific software',
            ],
            [
                'item_category_id' => 24,
                'unit_of_measure_id' => 10,
                'item_code' => "43230000-SFT-016",
                'item_name' => 'Information exchange software',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103105-CA-C04",
                'item_name' => 'INK CART, CANON CL-741, Col.',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103105-CA-C02",
                'item_name' => 'INK CART, CANON CL-811, Colored',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103105-CA-B04",
                'item_name' => 'INK CART, CANON PG-740, Black',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103105-CA-B02",
                'item_name' => 'INK CART, CANON PG-810, Black',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103105-EP-B17",
                'item_name' => 'INK CART, EPSON C13T664100 (T6641), Black',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103105-EP-C17",
                'item_name' => 'INK CART, EPSON C13T664200 (T6642), Cyan',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103105-EP-M17",
                'item_name' => 'INK CART, EPSON C13T664300 (T6643), Magenta',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103105-EP-Y17",
                'item_name' => 'INK CART, EPSON C13T664400 (T6644), Yellow',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103105-HP-B40",
                'item_name' => 'INK CART, HP C2P04AA (HP62) Black',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103105-HP-T40",
                'item_name' => 'INK CART, HP C2P06AA (HP62) Tri-color',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103105-HP-B09",
                'item_name' => 'INK CART, HP C9351AA, (HP21), Black',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103105-HP-T10",
                'item_name' => 'INK CART, HP C9352AA, (HP22), Tri-color',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103105-HP-T30",
                'item_name' => 'INK CART, HP C9363WA, (HP97), Tri-color',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103105-HP-P48",
                'item_name' => 'INK CART, HP C9397A (HP72) 69ml Photo Black',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103105-HP-C48",
                'item_name' => 'INK CART, HP C9398A (HP72) 69ml Cyan',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103105-HP-M48",
                'item_name' => 'INK CART, HP C9399A (HP72) 69ml Magenta',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103105-HP-Y48",
                'item_name' => 'INK CART, HP C9400A (HP72) 69ml Yellow',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103105-HP-G48",
                'item_name' => 'INK CART, HP C9401A (HP72) 69ml Gray',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103105-HP-B48",
                'item_name' => 'INK CART, HP C9403A (HP72) 130ml Matte Black',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103105-HP-B17",
                'item_name' => 'INK CART, HP CC640WA, (HP60), Black',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103105-HP-T17",
                'item_name' => 'INK CART, HP CC643WA, (HP60), Tri-color',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103105-HP-B35",
                'item_name' => 'INK CART, HP CD887AA, (HP703), Black',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103105-HP-T35",
                'item_name' => 'INK CART, HP CD888AA, (HP703), Tri-color',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103105-HX-C40",
                'item_name' => 'INK CART, HP CD972AA, (HP 920XL), Cyan',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103105-HX-M40",
                'item_name' => 'INK CART, HP CD973AA, (HP 920XL), Magenta',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103105-HX-Y40",
                'item_name' => 'INK CART, HP CD974AA, (HP 920XL), Yellow',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103105-HX-B40",
                'item_name' => 'INK CART, HP CD975AA, (HP 920XL), Black',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103105-HP-B20",
                'item_name' => 'INK CART, HP CH561WA, (HP61), Black',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103105-HP-T20",
                'item_name' => 'INK CART, HP CH562WA, (HP61), Tricolor',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103105-HP-B49",
                'item_name' => 'INK CART, HP CH565A (HP82) Black',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103105-HP-C49",
                'item_name' => 'INK CART, HP CH566A (HP82) Cyan',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103105-HP-M49",
                'item_name' => 'INK CART, HP CH567A (HP82) Magenta',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103105-HP-Y49",
                'item_name' => 'INK CART, HP CH568A (HP82) Yellow',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103105-HX-B43",
                'item_name' => 'INK CART, HP CN045AA, (HP950XL), Black',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103105-HX-C43",
                'item_name' => 'INK CART, HP CN046AA, (HP951XL), Cyan',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103105-HX-M43",
                'item_name' => 'INK CART, HP CN047AA, (HP951XL), Magenta',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103105-HX-Y43",
                'item_name' => 'INK CART, HP CN048AA, (HP951XL). Yellow',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103105-HP-B36",
                'item_name' => 'INK CART, HP CN692AA, (HP704), Black',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103105-HP-T36",
                'item_name' => 'INK CART, HP CN693AA, (HP704), Tri-color',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103105-HP-B33",
                'item_name' => 'INK CART, HP CZ107AA, (HP678), Black',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103105-HP-T33",
                'item_name' => 'INK CART, HP CZ108AA, (HP678), Tricolor',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103105-HP-B42",
                'item_name' => 'INK CART, HP CZ121A (HP685A), Black',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103105-HP-C33",
                'item_name' => 'INK CART, HP CZ122A (HP685A), Cyan',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103105-HP-M33",
                'item_name' => 'INK CART, HP CZ123A (HP685A), Magenta',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103105-HP-Y33",
                'item_name' => 'INK CART, HP CZ124A (HP685A), Yellow',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103105-HP-T43",
                'item_name' => 'INK CART, HP F6V26AA (HP680) Tri-color',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103105-HP-B43",
                'item_name' => 'INK CART, HP F6V27AA (HP680) Black',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103105-HP-C50",
                'item_name' => 'INK CART, HP L0S51AA (HP955) Cyan Original',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103105-HP-M50",
                'item_name' => 'INK CART, HP L0S54AA (HP955) Magenta Original',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103105-HP-Y50",
                'item_name' => 'INK CART, HP L0S57AA (HP955) Yellow Original',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103105-HP-B50",
                'item_name' => 'INK CART, HP L0S60AA (HP955) Black Original',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103105-HX-C48",
                'item_name' => 'INK CART, HP L0S63AA (HP955XL) Cyan Original',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103105-HX-M48",
                'item_name' => 'INK CART, HP L0S66AA (HP955XL) Magenta Original',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103105-HX-Y48",
                'item_name' => 'INK CART, HP L0S69AA (HP955XL) Yellow Original',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103105-HX-B48",
                'item_name' => 'INK CART, HP L0S72AA (HP955XL) Black Original',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103105-HP-C51",
                'item_name' => 'INK CART, HP T6L89AA (HP905) Cyan Original',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103105-HP-M51",
                'item_name' => 'INK CART, HP T6L93AA (HP905) Magenta Original',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103105-HP-Y51",
                'item_name' => 'INK CART, HP T6L97AA (HP905) Yellow Original',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103105-HP-B51",
                'item_name' => 'INK CART, HP T6M01AA (HP905) Black Original',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103105-HX-C49",
                'item_name' => 'INK CART, HP T6M05AA (HP905XL) Cyan Original',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103105-HX-M49",
                'item_name' => 'INK CART, HP T6M09AA (HP905XL) Magenta Original',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103105-HX-Y49",
                'item_name' => 'INK CART, HP T6M13AA (HP905XL) Yellow Original',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103105-HX-B49",
                'item_name' => 'INK CART, HP T6M17AA (HP905XL) Black Original',
            ],
            [
                'item_category_id' => 20,
                'unit_of_measure_id' => 1,
                'item_code' => "10191509-IN-A01",
                'item_name' => 'INSECTICIDE, aerosol type, net content: 600ml min',
            ],
            [
                'item_category_id' => 12,
                'unit_of_measure_id' => 20,
                'item_code' => "43211503-LCT-02",
                'item_name' => 'Laptop Computer, branded',
            ],
            [
                'item_category_id' => 13,
                'unit_of_measure_id' => 15,
                'item_code' => "39101628-LB-L01",
                'item_name' => 'Ligth Bulb, LED, 7 watts 1 pc in individual box',
            ],
            [
                'item_category_id' => 19,
                'unit_of_measure_id' => 6,
                'item_code' => "14111609-LL-C01",
                'item_name' => 'LOOSELEAF COVER, made of chipboard, for legal',
            ],
            [
                'item_category_id' => 16,
                'unit_of_measure_id' => 15,
                'item_code' => "44111515-MF-B02",
                'item_name' => 'MAGAZINE FILE BOX, LARGE size, made of chipboard',
            ],
            [
                'item_category_id' => 16,
                'unit_of_measure_id' => 18,
                'item_code' => "44121716-MA-F01",
                'item_name' => 'MARKER, FLUORESCENT, 3 assorted colors per set',
            ],
            [
                'item_category_id' => 16,
                'unit_of_measure_id' => 15,
                'item_code' => "44121708-MP-B01",
                'item_name' => 'MARKER, PERMANENT, bullet type, black',
            ],
            [
                'item_category_id' => 16,
                'unit_of_measure_id' => 15,
                'item_code' => "44121708-MP-B02",
                'item_name' => 'MARKER, PERMANENT, bullet type, blue',
            ],
            [
                'item_category_id' => 16,
                'unit_of_measure_id' => 15,
                'item_code' => "44121708-MP-B03",
                'item_name' => 'MARKER, PERMANENT, bullet type, red',
            ],
            [
                'item_category_id' => 16,
                'unit_of_measure_id' => 15,
                'item_code' => "44121708-MW-B01",
                'item_name' => 'MARKER, whiteboard, black, felt tip, bullet type',
            ],
            [
                'item_category_id' => 16,
                'unit_of_measure_id' => 15,
                'item_code' => "44121708-MW-B02",
                'item_name' => 'MARKER, whiteboard, blue, felt tip, bullet type',
            ],
            [
                'item_category_id' => 16,
                'unit_of_measure_id' => 15,
                'item_code' => "44121708-MW-B03",
                'item_name' => 'MARKER, whiteboard, red, felt tip, bullet type',
            ],
            [
                'item_category_id' => 4,
                'unit_of_measure_id' => 20,
                'item_code' => "47121804-MP-B01",
                'item_name' => 'MOP BUCKET, heavy duty, hard plastic',
            ],
            [
                'item_category_id' => 4,
                'unit_of_measure_id' => 15,
                'item_code' => "47131613-MP-H02",
                'item_name' => 'MOPHANDLE, heavy duty, aluminum, screw type',
            ],
            [
                'item_category_id' => 4,
                'unit_of_measure_id' => 15,
                'item_code' => "47131619-MP-R01",
                'item_name' => 'MOPHEAD, made of rayon, weight: 400 grams min',
            ],
            [
                'item_category_id' => 12,
                'unit_of_measure_id' => 20,
                'item_code' => "43211708-MO-O01",
                'item_name' => 'MOUSE, optical, USB connection type',
            ],
            [
                'item_category_id' => 2,
                'unit_of_measure_id' => 20,
                'item_code' => "45111609-MM-P01",
                'item_name' => 'MULTIMEDIA PROJECTOR, 4000 min ANSI Lumens',
            ],
            [
                'item_category_id' => 24,
                'unit_of_measure_id' => 10,
                'item_code' => "43230000-SFT-010",
                'item_name' => 'Network applications software',
            ],
            [
                'item_category_id' => 24,
                'unit_of_measure_id' => 10,
                'item_code' => "43230000-SFT-011",
                'item_name' => 'Network management software',
            ],
            [
                'item_category_id' => 12,
                'unit_of_measure_id' => 20,
                'item_code' => "",
                'item_name' => 'Network Routers',
            ],
            [
                'item_category_id' => 24,
                'unit_of_measure_id' => 10,
                'item_code' => "43230000-SFT-012",
                'item_name' => 'Networking software',
            ],
            [
                'item_category_id' => 19,
                'unit_of_measure_id' => 13,
                'item_code' => "14111514-NP-S02",
                'item_name' => 'NOTE PAD, stick on, 50mm x 76mm (2" x 3") min',
            ],
            [
                'item_category_id' => 19,
                'unit_of_measure_id' => 13,
                'item_code' => "14111514-NP-S04",
                'item_name' => 'NOTE PAD, stick on, 76mm x 100mm (3" x 4") min',
            ],
            [
                'item_category_id' => 19,
                'unit_of_measure_id' => 13,
                'item_code' => "14111514-NP-S03",
                'item_name' => 'NOTE PAD, stick on, 76mm x 76mm (3" x 3") min',
            ],
            [
                'item_category_id' => 19,
                'unit_of_measure_id' => 15,
                'item_code' => "14111514-NB-S01",
                'item_name' => 'NOTEBOOK, STENOGRAPHER, spiral, 40 leaves',
            ],
            [
                'item_category_id' => 24,
                'unit_of_measure_id' => 10,
                'item_code' => "43230000-SFT-013",
                'item_name' => 'Operating environment software',
            ],
            [
                'item_category_id' => 16,
                'unit_of_measure_id' => 5,
                'item_code' => "44122104-PC-G01",
                'item_name' => 'PAPER CLIP, vinyl/plastic coat, length: 32mm min',
            ],
            [
                'item_category_id' => 16,
                'unit_of_measure_id' => 5,
                'item_code' => "44122104-PC-J02",
                'item_name' => 'PAPER CLIP, vinyl/plastic coat, length: 48mm min',
            ],
            [
                'item_category_id' => 16,
                'unit_of_measure_id' => 20,
                'item_code' => "44101603-PS-M01",
                'item_name' => 'PAPER SHREDDER, cutting width: 3mm-4mm (Entry Level)',
            ],
            [
                'item_category_id' => 16,
                'unit_of_measure_id' => 20,
                'item_code' => "44101603-PS-M02",
                'item_name' => 'PAPER SHREDDER, cutting width: 3mm-4mm (Mid-Level)',
            ],
            [
                'item_category_id' => 16,
                'unit_of_measure_id' => 20,
                'item_code' => "44101601-PT-M01",
                'item_name' => 'PAPER TRIMMER/CUTTING MACHINE, max paper size: B4',
            ],
            [
                'item_category_id' => 19,
                'unit_of_measure_id' => 16,
                'item_code' => "14111507-PP-M01",
                'item_name' => 'PAPER, MULTICOPY, 80gsm, size: 210mm x 297mm',
            ],
            [
                'item_category_id' => 19,
                'unit_of_measure_id' => 16,
                'item_code' => "14111507-PP-M02",
                'item_name' => 'PAPER, MULTICOPY, 80gsm, size: 216mm x 330mm',
            ],
            [
                'item_category_id' => 19,
                'unit_of_measure_id' => 16,
                'item_code' => "14111507-PP-C01",
                'item_name' => 'PAPER, Multi-Purpose (COPY) A4, 70 gsm',
            ],
            [
                'item_category_id' => 19,
                'unit_of_measure_id' => 16,
                'item_code' => "14111507-PP-C02",
                'item_name' => 'PAPER, Multi-Purpose (COPY) Legal, 70 gsm',
            ],
            [
                'item_category_id' => 19,
                'unit_of_measure_id' => 13,
                'item_code' => "14111531-PP-R01",
                'item_name' => 'PAPER, PAD, ruled, size: 216mm x 330mm (± 2mm)',
            ],
            [
                'item_category_id' => 19,
                'unit_of_measure_id' => 16,
                'item_code' => "14111503-PA-P01",
                'item_name' => 'PAPER, PARCHMENT, size: 210 x 297mm, multi-purpose',
            ],
            [
                'item_category_id' => 19,
                'unit_of_measure_id' => 17,
                'item_code' => "14111818-TH-P02",
                'item_name' => 'PAPER, THERMAL, 55gsm, size: 216mm±1mm x 30m-0.3m',
            ],
            [
                'item_category_id' => 16,
                'unit_of_measure_id' => 15,
                'item_code' => "44121619-PS-M01",
                'item_name' => 'PENCIL SHARPENER, manual, single cutter head',
            ],
            [
                'item_category_id' => 16,
                'unit_of_measure_id' => 5,
                'item_code' => "44121706-PE-L01",
                'item_name' => 'PENCIL, lead, w/ eraser, wood cased, hardness: HB',
            ],
            [
                'item_category_id' => 9,
                'unit_of_measure_id' => 15,
                'item_code' => "55121905-PH-F01",
                'item_name' => 'PHILIPPINE NATIONAL FLAG, 100% polyester',
            ],
            [
                'item_category_id' => 25,
                'unit_of_measure_id' => 8,
                'item_code' => "51471505-PO-P01",
                'item_name' => 'POVIDONE IODINE, 10 % solution, 120 ml',
            ],
            [
                'item_category_id' => 12,
                'unit_of_measure_id' => 20,
                'item_code' => "43212102-PR-D02",
                'item_name' => 'PRINTER, IMPACT DOT MATRIX, 24 pins, 136 column',
            ],
            [
                'item_category_id' => 12,
                'unit_of_measure_id' => 20,
                'item_code' => "43212102-PR-D01",
                'item_name' => 'PRINTER, IMPACT DOT MATRIX, 9 pins, 80 columns',
            ],
            [
                'item_category_id' => 12,
                'unit_of_measure_id' => 20,
                'item_code' => "",
                'item_name' => 'PRINTER, Inkjet, Color',
            ],
            [
                'item_category_id' => 12,
                'unit_of_measure_id' => 15,
                'item_code' => "",
                'item_name' => 'PRINTER, Inkjet, Monochrome',
            ],
            [
                'item_category_id' => 12,
                'unit_of_measure_id' => 20,
                'item_code' => "",
                'item_name' => 'PRINTER, LASER, Color',
            ],
            [
                'item_category_id' => 12,
                'unit_of_measure_id' => 20,
                'item_code' => "43212105-PR-L01",
                'item_name' => 'PRINTER, LASER, monochrome, network-ready',
            ],
            [
                'item_category_id' => 16,
                'unit_of_measure_id' => 15,
                'item_code' => "44101602-PU-P01",
                'item_name' => 'PUNCHER, paper, heavy duty, with two hole guide',
            ],
            [
                'item_category_id' => 4,
                'unit_of_measure_id' => 6,
                'item_code' => "47131501-RG-C01",
                'item_name' => 'RAGS, all cotton, 32 pieces per kilogram min',
            ],
            [
                'item_category_id' => 19,
                'unit_of_measure_id' => 3,
                'item_code' => "14111531-RE-B01",
                'item_name' => 'RECORD BOOK, 300 PAGES, size: 214mm x 278mm min',
            ],
            [
                'item_category_id' => 19,
                'unit_of_measure_id' => 3,
                'item_code' => "14111531-RE-B02",
                'item_name' => 'RECORD BOOK, 500 PAGES, size: 214mm x 278mm min',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103112-EP-R05",
                'item_name' => 'RIBBON CART, EPSON C13S015516 (#8750), Black',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103112-EP-R07",
                'item_name' => 'RIBBON CART, EPSON C13S015531 (S015086), Black',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103112-EP-R13",
                'item_name' => 'RIBBON CART, EPSON C13S015632, Black, forLX-310',
            ],
            [
                'item_category_id' => 16,
                'unit_of_measure_id' => 6,
                'item_code' => "44122037-RB-P10",
                'item_name' => 'RING BINDER, 80 rings, plastic, 32mm x 1.12m',
            ],
            [
                'item_category_id' => 16,
                'unit_of_measure_id' => 5,
                'item_code' => "44122101-RU-B01",
                'item_name' => 'RUBBER BAND, 70mm min lay flat length (#18)',
            ],
            [
                'item_category_id' => 15,
                'unit_of_measure_id' => 15,
                'item_code' => "41111604-RU-P02",
                'item_name' => 'RULER, plastic, 450mm (18"), width: 38mm min',
            ],
            [
                'item_category_id' => 16,
                'unit_of_measure_id' => 14,
                'item_code' => "44121618-SS-S01",
                'item_name' => 'SCISSORS, symmetrical, blade length: 65mm min',
            ],
            [
                'item_category_id' => 4,
                'unit_of_measure_id' => 12,
                'item_code' => "47131602-SC-N01",
                'item_name' => 'SCOURING PAD, made of synthetic nylon, 140 x 220mm',
            ],
            [
                'item_category_id' => 24,
                'unit_of_measure_id' => 10,
                'item_code' => "43230000-SFT-014",
                'item_name' => 'Security and protection software',
            ],
            [
                'item_category_id' => 1,
                'unit_of_measure_id' => 15,
                'item_code' => "60121524-SP-G01",
                'item_name' => 'SIGN PEN, BLACK, liquid/gel ink, 0.5mm needle tip',
            ],
            [
                'item_category_id' => 1,
                'unit_of_measure_id' => 15,
                'item_code' => "60121524-SP-G02",
                'item_name' => 'SIGN PEN, BLUE, liquid/gel ink, 0.5mm needle tip',
            ],
            [
                'item_category_id' => 1,
                'unit_of_measure_id' => 15,
                'item_code' => "60121524-SP-G03",
                'item_name' => 'SIGN PEN, RED, liquid/gel ink, 0.5mm needle tip',
            ],
            [
                'item_category_id' => 5,
                'unit_of_measure_id' => 4,
                'item_code' => "12171703-SI-P01",
                'item_name' => 'STAMP PAD INK, purple or violet',
            ],
            [
                'item_category_id' => 16,
                'unit_of_measure_id' => 15,
                'item_code' => "44121905-SP-F01",
                'item_name' => 'STAMP PAD, FELT, bed dimension: 60mm x 100mm min',
            ],
            [
                'item_category_id' => 16,
                'unit_of_measure_id' => 15,
                'item_code' => "44121613-SR-P01",
                'item_name' => 'STAPLE REMOVER, PLIER-TYPE',
            ],
            [
                'item_category_id' => 14,
                'unit_of_measure_id' => 5,
                'item_code' => "31151804-SW-H01",
                'item_name' => 'STAPLE WIRE, for heavy duty staplers, (23/13)',
            ],
            [
                'item_category_id' => 14,
                'unit_of_measure_id' => 5,
                'item_code' => "31151804-SW-S01",
                'item_name' => 'STAPLE WIRE, STANDARD, (26/6)',
            ],
            [
                'item_category_id' => 16,
                'unit_of_measure_id' => 20,
                'item_code' => "44121615-ST-B01",
                'item_name' => 'STAPLER, BINDER TYPE, heavy duty, desktop',
            ],
            [
                'item_category_id' => 16,
                'unit_of_measure_id' => 15,
                'item_code' => "44121615-ST-S01",
                'item_name' => 'STAPLER, STANDARD TYPE, load cap: 200 staples min',
            ],
            [
                'item_category_id' => 10,
                'unit_of_measure_id' => 20,
                'item_code' => "56101519-TM-S02",
                'item_name' => 'TABLE, MONOBLOC, BEIGE, 889 x 889mm (35" x 35")min',
            ],
            [
                'item_category_id' => 10,
                'unit_of_measure_id' => 20,
                'item_code' => "56101519-TM-S01",
                'item_name' => 'TABLE, MONOBLOC, WHITE, 889 x 889mm (35" x 35")min',
            ],
            [
                'item_category_id' => 16,
                'unit_of_measure_id' => 15,
                'item_code' => "44121605-TD-T01",
                'item_name' => 'TAPE DISPENSER, TABLE TOP, for 24mm width tape',
            ],
            [
                'item_category_id' => 14,
                'unit_of_measure_id' => 17,
                'item_code' => "31201502-TA-E01",
                'item_name' => 'TAPE, ELECTRICAL, 18mm x 16M min',
            ],
            [
                'item_category_id' => 14,
                'unit_of_measure_id' => 17,
                'item_code' => "31201503-TA-M01",
                'item_name' => 'TAPE, MASKING, width: 24mm (±1mm)',
            ],
            [
                'item_category_id' => 14,
                'unit_of_measure_id' => 17,
                'item_code' => "31201503-TA-M02",
                'item_name' => 'TAPE, MASKING, width: 48mm (±1mm)',
            ],
            [
                'item_category_id' => 14,
                'unit_of_measure_id' => 17,
                'item_code' => "31201517-TA-P01",
                'item_name' => 'TAPE, PACKAGING, width: 48mm (±1mm)',
            ],
            [
                'item_category_id' => 14,
                'unit_of_measure_id' => 17,
                'item_code' => "31201512-TA-T01",
                'item_name' => 'TAPE, TRANSPARENT, width: 24mm (±1mm)',
            ],
            [
                'item_category_id' => 14,
                'unit_of_measure_id' => 17,
                'item_code' => "31201512-TA-T02",
                'item_name' => 'TAPE, TRANSPARENT, width: 48mm (±1mm)',
            ],
            [
                'item_category_id' => 19,
                'unit_of_measure_id' => 12,
                'item_code' => "14111704-TT-P01",
                'item_name' => 'TOILET TISSUE PAPER 2-plys sheets, 150 pulls',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103103-BR-B03",
                'item_name' => 'TONER CART, BROTHER TN-2025, Black',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103103-BR-B04",
                'item_name' => 'TONER CART, BROTHER TN-2130, Black',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103103-BR-B05",
                'item_name' => 'TONER CART, BROTHER TN-2150, Black',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103103-BR-B09",
                'item_name' => 'TONER CART, BROTHER TN-3320, Black',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103103-BR-B11",
                'item_name' => 'TONER CART, BROTHER TN-3350, Black, for HL5450DN (CU Printer)',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103103-HP-B12",
                'item_name' => 'TONER CART, HP CB435A, Black',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103103-HP-B14",
                'item_name' => 'TONER CART, HP CB540A, Black',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103103-HP-B18",
                'item_name' => 'TONER CART, HP CE255A, Black',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103103-HP-B21",
                'item_name' => 'TONER CART, HP CE278A, Black',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103103-HP-B22",
                'item_name' => 'TONER CART, HP CE285A (HP85A), Black',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103103-HP-B23",
                'item_name' => 'TONER CART, HP CE310A, Black',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103103-HP-C23",
                'item_name' => 'TONER CART, HP CE311A, Cyan',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103103-HP-Y23",
                'item_name' => 'TONER CART, HP CE312A, Yellow',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103103-HP-M23",
                'item_name' => 'TONER CART, HP CE313A, Magenta',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103103-HP-B24",
                'item_name' => 'TONER CART, HP CE320A, Black',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103103-HP-C24",
                'item_name' => 'TONER CART, HP CE321A, Cyan',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103103-HP-Y24",
                'item_name' => 'TONER CART, HP CE322A, Yellow',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103103-HP-M24",
                'item_name' => 'TONER CART, HP CE323A, Magenta',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103103-HP-B25",
                'item_name' => 'TONER CART, HP CE390A, Black',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103103-HP-B26",
                'item_name' => 'TONER CART, HP CE400A, Black',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103103-HP-C26",
                'item_name' => 'TONER CART, HP CE401A, Cyan',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103103-HP-Y26",
                'item_name' => 'TONER CART, HP CE402A, Yellow',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103103-HP-M26",
                'item_name' => 'TONER CART, HP CE403A, Magenta',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103103-HP-B27",
                'item_name' => 'TONER CART, HP CE410A, (HP305), Black',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103103-HP-C27",
                'item_name' => 'TONER CART, HP CE411A, (HP305), Cyan',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103103-HP-Y27",
                'item_name' => 'TONER CART, HP CE412A, (HP305), Yellow',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103103-HP-M27",
                'item_name' => 'TONER CART, HP CE413A, (HP305), Magenta',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103103-HP-B28",
                'item_name' => 'TONER CART, HP CE505A, Black',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103103-HX-B28",
                'item_name' => 'TONER CART, HP CE505X, Black, high cap',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103103-HP-B52",
                'item_name' => 'TONER CART, HP CF217A (HP17A) Black LaserJet',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103103-HP-B53",
                'item_name' => 'TONER CART, HP CF226A (HP26A) Black LaserJet',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103103-HX-B50",
                'item_name' => 'TONER CART, HP CF226XC (HP26XC) Black LaserJet',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103103-HP-B55",
                'item_name' => 'TONER CART, HP CF280A, LaserJet Pro M401/M425 2.7K Black',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103103-HP-B51",
                'item_name' => 'TONER CART, HP CF280XC',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103103-HP-B56",
                'item_name' => 'TONER CART, HP CF281A (HP81A) Black LaserJet',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103103-HP-B57",
                'item_name' => 'TONER CART, HP CF283A (HP83A) LaserJet Black',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103103-HX-B51",
                'item_name' => 'TONER CART, HP CF283XC (HP83X) Blk Contract LJ',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103103-HP-B58",
                'item_name' => 'TONER CART, HP CF287A (HP87) black',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103103-HP-B59",
                'item_name' => 'TONER CART, HP CF310AC (HP826) black',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103103-HP-C59",
                'item_name' => 'TONER CART, HP CF311AC (HP826) cyan',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103103-HP-Y59",
                'item_name' => 'TONER CART, HP CF312AC (HP826) yellow',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103103-HP-M59",
                'item_name' => 'TONER CART, HP CF313AC (HP826) magenta',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103103-HX-B52",
                'item_name' => 'TONER CART, HP CF325XC (HP25X) Black LaserJet',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103103-HP-B60",
                'item_name' => 'TONER CART, HP CF350A Black LJ',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103103-HP-C60",
                'item_name' => 'TONER CART, HP CF351A Cyan LJ',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103103-HP-Y60",
                'item_name' => 'TONER CART, HP CF352A Yellow LJ',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103103-HP-M60",
                'item_name' => 'TONER CART, HP CF353A Magenta LJ',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103103-HP-B61",
                'item_name' => 'TONER CART, HP CF360A (HP508A) Black LaserJet',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103103-HX-B53",
                'item_name' => 'TONER CART, HP CF360XC (HP508X) Black Contract LJ',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103103-HP-C61",
                'item_name' => 'TONER CART, HP CF361A (HP508A) Cyan LaserJet',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103103-HX-C53",
                'item_name' => 'TONER CART, HP CF361XC (HP508X) Cyan Contract LJ',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103103-HP-Y61",
                'item_name' => 'TONER CART, HP CF362A (HP508A) Yellow LaserJet',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103103-HX-Y53",
                'item_name' => 'TONER CART, HP CF362XC (HP508X) Yellow Contract LJ',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103103-HP-M61",
                'item_name' => 'TONER CART, HP CF363A (HP508A) Magenta LaserJet',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103103-HX-M53",
                'item_name' => 'TONER CART, HP CF363XC (HP508X) Magenta Contract LJ',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103103-HP-B62",
                'item_name' => 'TONER CART, HP CF400A (HP201A) Black LaserJet',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103103-HP-C62",
                'item_name' => 'TONER CART, HP CF401A (HP201A) Cyan LaserJet',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103103-HP-Y62",
                'item_name' => 'TONER CART, HP CF402A (HP201A) Yellow LaserJet',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103103-HP-M62",
                'item_name' => 'TONER CART, HP CF403A (HP201A) Magenta LaserJet',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103103-HP-B63",
                'item_name' => 'TONER CART, HP CF410A (HP410A) black',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103103-HX-B54",
                'item_name' => 'TONER CART, HP CF410XC (HP410XC) black',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103103-HP-C63",
                'item_name' => 'TONER CART, HP CF411A (HP410A) cyan',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103103-HX-C54",
                'item_name' => 'TONER CART, HP CF411XC (HP410XC) cyan',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103103-HP-Y63",
                'item_name' => 'TONER CART, HP CF412A (HP410A) yellow',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103103-HX-Y54",
                'item_name' => 'TONER CART, HP CF412XC (HP410XC) yellow',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103103-HP-M63",
                'item_name' => 'TONER CART, HP CF413A (HP410A) magenta',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103103-HX-M54",
                'item_name' => 'TONER CART, HP CF413XC (HP410XC) magenta',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103103-HP-B34",
                'item_name' => 'TONER CART, HP Q2612A, Black',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103103-HP-B39",
                'item_name' => 'TONER CART, HP Q5942A, Black',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103103-HP-B48",
                'item_name' => 'TONER CART, HP Q7553A, Black',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103103-LX-B03",
                'item_name' => 'TONER CART, LEXMARK E360H11P, Black',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103103-LX-B05",
                'item_name' => 'TONER CART, LEXMARK T650A11P, Black',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103103-SA-B06",
                'item_name' => 'TONER CART, SAMSUNG MLT-D101S, Black',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103103-SA-B07",
                'item_name' => 'TONER CART, SAMSUNG MLT-D103S, Black',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103103-SA-B08",
                'item_name' => 'TONER CART, SAMSUNG MLT-D104S, Black',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103103-SA-B09",
                'item_name' => 'TONER CART, SAMSUNG MLT-D105L, Black',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103103-SA-B14",
                'item_name' => 'TONER CART, SAMSUNG MLT-D108S, Black',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103103-SA-B21",
                'item_name' => 'TONER CART, SAMSUNG MLT-D203E, Black',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103103-SA-B18",
                'item_name' => 'TONER CART, SAMSUNG MLT-D203L, Black',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103103-SA-B20",
                'item_name' => 'TONER CART, SAMSUNG MLT-D203U, black',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103103-SA-B12",
                'item_name' => 'TONER CART, SAMSUNG MLT-D205E, Black',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103103-SA-B05",
                'item_name' => 'TONER CART, SAMSUNG MLT-D205L, Black',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103103-SA-B10",
                'item_name' => 'TONER CART, SAMSUNG SCX-D6555A, Black',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103103-BR-B15",
                'item_name' => 'TONER CARTRIDGE, BROTHER TN-3478, Blackf, for printer HL-6400DW (12,000 pages)',
            ],
            [
                'item_category_id' => 22,
                'unit_of_measure_id' => 7,
                'item_code' => "44103103-CA-B00",
                'item_name' => 'TONER CARTRIDGE, CANON 324 II, for printer LBP6780x',
            ],
            [
                'item_category_id' => 4,
                'unit_of_measure_id' => 17,
                'item_code' => "47121701-TB-P02",
                'item_name' => 'TRASHBAG, plastic, transparent',
            ],
            [
                'item_category_id' => 14,
                'unit_of_measure_id' => 17,
                'item_code' => "31151507-TW-P01",
                'item_name' => 'TWINE, plastic, one (1) kilo per roll',
            ],
            [
                'item_category_id' => 24,
                'unit_of_measure_id' => 10,
                'item_code' => "43230000-SFT-015",
                'item_name' => 'Utility and device driver software',
            ],
            [
                'item_category_id' => 4,
                'unit_of_measure_id' => 15,
                'item_code' => "47121702-WB-P01",
                'item_name' => 'WASTEBASKET, non-rigid plastic',
            ],
            [
                'item_category_id' => 12,
                'unit_of_measure_id' => 20,
                'item_code' => "",
                'item_name' => 'Wireless Access Point',
            ],
            [
                'item_category_id' => 1,
                'unit_of_measure_id' => 12,
                'item_code' => "60121124-WR-P01",
                'item_name' => 'WRAPPING PAPER, kraft, 65gsm (-5%)',
            ],

        ];

        foreach ($items as $item) {
            $createdItem = Item::create($item);
            echo "item name: ".$createdItem->item_name." item code: ".$createdItem->item_code."\n";
        }
    }
}
